<a href="https://colab.research.google.com/github/KennethTBarrett/DS-Unit-1-Sprint-2-Statistics/blob/master/Copy_of_LS_DS_121_Statistics_Probability_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 1 Sprint 2 Assignment 1*

# Apply the t-test to real data

Your assignment is to determine which issues have "statistically significant" differences between political parties in this [1980s congressional voting data](https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records). The data consists of 435 instances (one for each congressperson), a class (democrat or republican), and 16 binary attributes (yes or no for voting for or against certain issues). Be aware - there are missing values!

Your goals:

1. Load and clean the data (or determine the best method to drop observations when running tests)
2. Using hypothesis testing, find an issue that democrats support more than republicans with p < 0.01
3. Using hypothesis testing, find an issue that republicans support more than democrats with p < 0.01
4. Using hypothesis testing, find an issue where the difference between republicans and democrats has p > 0.1 (i.e. there may not be much of a difference)

Note that this data will involve *2 sample* t-tests, because you're comparing averages across two groups (republicans and democrats) rather than a single group against a null hypothesis.

Stretch goals:

1. Refactor your code into functions so it's easy to rerun with arbitrary variables
2. Apply hypothesis testing to your personal project data (for the purposes of this notebook you can type a summary of the hypothesis you formed and tested)

In [110]:
import pandas as pd
import numpy as np

!curl https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data > votes.data

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18171  100 18171    0     0  54404      0 --:--:-- --:--:-- --:--:-- 54404

In [0]:
df = pd.read_csv('votes.data')

df = df.replace('?', np.NaN)

In [0]:
df.columns = ['Party', 'Handicap_Infants', 'Water_Proj_Cost_Share', 'Adoption_of_Budget_Res', 'Dr_Fee_Freeze', 'ElSal_Aid', 'Relig_Grp_Schools', 'Anti_Sat_Test_Ban', 'Nic_Aid', 'Mx-Missile', 'Immig', 'SynFuel_Corp_Cutback', 'Edu_Spend', 'Superfund_Right_Sue', 'Crime', 'Duty_Free_Exports', 'Export_Admin_Act_South_Afr']

In [0]:
df = df.dropna()

In [114]:
df = df.replace('n', 0)
df = df.replace('y', 1)
df.sample(50)

          Party  ...  Export_Admin_Act_South_Afr
361    democrat  ...                           1
118  republican  ...                           0
34   republican  ...                           0
159    democrat  ...                           1
337    democrat  ...                           1
204    democrat  ...                           1
7    republican  ...                           1
84     democrat  ...                           1
134  republican  ...                           0
410    democrat  ...                           1
121  republican  ...                           1
72   republican  ...                           1
183    democrat  ...                           1
209    democrat  ...                           1
336    democrat  ...                           1
213  republican  ...                           1
325    democrat  ...                           1
54   republican  ...                           0
29   republican  ...                           0
382    democrat  ...                           1
404  republican  ...                           1
52   republican  ...                           0
230  republican  ...                           1
252  republican  ...                           1
352  republican  ...                           1
92     democrat  ...                           1
339  republican  ...                           1
38     democrat  ...                           1
45     democrat  ...                           1
278  republican  ...                           0
229  republican  ...                           1
93     democrat  ...                           1
421    democrat  ...                           1
244    democrat  ...                           1
275  republican  ...                           0
37   republican  ...                           0
146    democrat  ...                           1
308    democrat  ...                           1
234  republican  ...                           1
216  republican  ...                           0
400  republican  ...                           0
4      democrat  ...                           1
395    democrat  ...                           1
311    democrat  ...                           1
301  republican  ...                           1
406    democrat  ...                           0
297    democrat  ...                           1
323  republican  ...                           0
65   republican  ...                           1
425    democrat  ...                           1

[50 rows x 17 columns]

In [0]:
from scipy.stats import ttest_ind

df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})

df = df.astype(int)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

In [116]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Handicap_Infants']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Handicap_Infants'])

0.2626669433008713

Handicap_Infants   0   1
Party
democrat          51  73
republican        85  23

In [118]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Water_Proj_Cost_Share']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Water_Proj_Cost_Share']) # P-Value >0.1 for this issue. There is not much difference.

0.9260249028441812

Water_Proj_Cost_Share   0   1
Party
democrat               68  56
republican             57  51

In [119]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Adoption_of_Budget_Res']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Adoption_of_Budget_Res']) # Democrats strongly favor this issue over republicans with a p-value of >0.1

0.16439939935642917

Adoption_of_Budget_Res   0    1
Party
democrat                18  106
republican              91   17

In [120]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Dr_Fee_Freeze']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Dr_Fee_Freeze']) # Republicans strongly favor this issue over republicans with a p-value of >0.1

0.6429620091750112

Dr_Fee_Freeze    0    1
Party
democrat       118    6
republican       1  107

In [121]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['ElSal_Aid']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['ElSal_Aid']) # Republicans strongly favor this issue over democrats with a p-value = <.1

0.06349964631412779

ElSal_Aid    0    1
Party
democrat    99   25
republican   5  103

In [122]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Relig_Grp_Schools']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Relig_Grp_Schools']) # Republicans favor this issue over democrats with a p-value = <0.01

0.00011839688314539908

Relig_Grp_Schools   0   1
Party
democrat           69  55
republican         14  94

In [124]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Anti_Sat_Test_Ban']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Anti_Sat_Test_Ban']) # Democrats favor this issue over republicans with a p-value = >0.1

0.13798882360253345

Anti_Sat_Test_Ban   0   1
Party
democrat           29  95
republican         79  29

In [125]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Nic_Aid']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Nic_Aid']) # Democrats strongly favor this issue over republicans with a p-value >.1

0.3080226834725156

Nic_Aid      0    1
Party
democrat    21  103
republican  92   16

In [126]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Mx-Missile']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Mx-Missile']) # Democrats strongly favor this issue over Republicans with a p-value = <.1

0.6429620091750112

Mx-Missile   0   1
Party
democrat    26  98
republican  93  15

In [128]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Immig']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Immig']) # There is not much difference on this issue between the 2 parties, with a p-value < 0.1

0.06349964631412779

Immig        0   1
Party
democrat    58  66
republican  46  62

In [0]:
'Duty_Free_Exports', 'Export_Admin_Act_South_Afr']

In [129]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['SynFuel_Corp_Cutback']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['SynFuel_Corp_Cutback']) # Republicans favor this issue over democrats with a p-value < 0.01

0.008032344399384867

SynFuel_Corp_Cutback   0   1
Party
democrat              61  63
republican            91  17

In [132]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Edu_Spend']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Edu_Spend']) # Republicans favor this issue over democrats with a p-value = 1

1.0

Edu_Spend     0   1
Party
democrat    108  16
republican   16  92

In [134]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Superfund_Right_Sue']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Superfund_Right_Sue']) # Republicans favor this issue over democrats with a p-value < 0.1

0.07799219440141697

Superfund_Right_Sue   0   1
Party
democrat             88  36
republican           17  91

In [133]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Crime']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Crime']) # Republicans strongly favor this issue over democrats with a p-value < 0.01

0.00011839688314539908

Crime        0    1
Party
democrat    81   43
republican   2  106

In [136]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
print(ttest_ind(df['Party'], df['Duty_Free_Exports']).pvalue)

df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Duty_Free_Exports']) # Democrats favor this issue over republicans with a p-value < 0.1

0.038468918266360654

Duty_Free_Exports   0   1
Party
democrat           50  74
republican         96  12

In [139]:
df['Party'] = df['Party'].replace({'democrat':0, 'republican': 1})
stat, pvalue = ttest_ind(df['Party'], df['Export_Admin_Act_South_Afr'])

print('{:f}'.format(pvalue))
df['Party'] = df['Party'].replace(0, 'democrat')
df['Party'] = df['Party'].replace(1, 'republican')

pd.crosstab(df['Party'], df['Export_Admin_Act_South_Afr']) # Democrats favor this issue over republicans with a p-value < 0.01

0.000000

Export_Admin_Act_South_Afr   0    1
Party
democrat                     7  117
republican                  36   72